# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake Vcpkg Publish

on:
  push:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc, cl ] # clang and clang++ for cpp_compiler
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            executable_name: "Chip8topia"
            executable_extension: ".exe"
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            executable_name: "Chip8topia"
            executable_extension: ""
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install libs
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev
          sudo apt-get install -y libglu1-mesa-dev

      - name: Install vcpgk
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ github.workspace }}/vcpkg
          runVcpkgInstall: true

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Create release folder
        run: mkdir -p ${{ github.workspace }}/release

      - name: Copy artifacts
        run: |
          mkdir ${{ matrix.executable_name }}-v${{ github.run_number }}
          if: matrix.os == 'ubuntu-latest'
            cp -r ${{ steps.strings.outputs.build-output-dir }}/${{ matrix.executable_name }}/${{ matrix.executable_name }} ${{ github.workspace }}/release/${{ matrix.executable_name }}-v${{ github.run_number }}
          else
            cp -r ${{ steps.strings.outputs.build-output-dir }}/${{ matrix.build_type }}/${{ matrix.executable_name }}${{ matrix.executable_extension }} ${{ github.workspace }}/release/${{ matrix.executable_name }}-v${{ github.run_number }}
          fi

      - name: Publish release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/release/${{ matrix.executable_name }}-v${{ github.run_number }}
          asset_name: ${{ matrix.executable_name }}-v${{ github.run_number }}
          asset_content_type: application/zip
          token: ${{ secrets.GITHUB_TOKEN }}