# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: vcpkg-cmake-publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildme:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: ubuntu-20.04
            vcpkg_triplet: x64-linux-release
          - os: macos-11
            vcpkg_triplet: x64-osx-release
          - os: windows-2019
            vcpkg_triplet: x64-windows-release
    steps:
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
          pkgs: boost-date-time
          triplet: ${{ matrix.config.vcpkg_triplet }}
          cache-key: ${{ matrix.config.os }}
          revision: master
          token: ${{ github.token }}
          github-binarycache: true

      - name: CMake configure
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ steps.vcpkg.outputs.toolchain_file }} -DVCPKG_TARGET_TRIPLET=${{ matrix.config.vcpkg_triplet }}
      - name: CMake build
        run: cmake --build build
      - name: CMake test
        run: cmake --build build --target test