name: Populate dependencies

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

env:
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      # This will execute a dry-run, meaning that libraries will not be built and
      # installed, but they will still be reported to the GitHub dependency graph.
      # This step assumes `vcpkg` has been bootstrapped (run `./vcpkg/bootstrap-vcpkg`)
      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install --dry-run